### ISSUE TITLE
Meeting with Himanshu

### ISSUE THREAD

**Issue by jesparent** [OREL-group/GSoC#28]
Detail / report back on meeting with Himanshu

**Comment by rv602** [comment]
I had a meeting with Himanshu regarding <a href='https://gist.github.com/himanshu-02/4c7a50718e27abcecade2766fc1bf218'>his last year’s project</a> and it’s implementation. 

He told that it was basically an attempt to demonstrate the phenomena of a contributor being promoted to a maintainer by solving issues and increasing the contributor's confidence points.

This is a simulation of the model : -

![Screen Recording 2023-07-01 at 4 49 54 PM](https://github.com/OREL-group/GSoC/assets/92572013/cc2426b5-9fcb-4ceb-b3b9-88f3816aa816)

As you can see in the simulation, there are 3 types of issues - `earth-shot`, `moon-shot` and `mars-jupiter shot`. They have been categorised according to their difficulty levels (increasing order).

A contributor receives 10, 20 and 50 confidence points for solving a `earth-shot`, `moon-shot` and `mars-jupiter shot` issue respectively.
Once a contributor attains 90 confidence points, he is promoted to a maintainer.

This model makes use of the Netlogo's Q-learning plugin.

Himanshu has suggested me to get a bit comfortable with RL, then try to create these models in Mesa using RL. Once this stage is reached, further work can be done on the model.

**Comment by jesparent** [comment]
nice - let's think about what the next steps are and make specific plans @rv602 @Orthogonal-Research-Lab
